LOCAL_PATH:= $(call my-dir)
include $(CLEAR_VARS)

#LOCAL_PATH = $(JNI_DIR)/../../../EmbeddedGIS
LOCAL_PATH =	$(Z11_PATH)/

LOCAL_MODULE:= EmbeddedGIS

LOCAL_CFLAGS += -O3  -DANDROID_NDK 

LOCAL_C_INCLUDES := $(LOCAL_PATH) \
	$(LOCAL_PATH)/ExternalLib/libcurlpp/include \
	$(LOCAL_PATH)/Platform/Android/prebuilt/libcurl/include


LOCAL_SRC_FILES:= \
	MapKit/Embedded/Application/AttributeMgr.cpp \
	MapKit/Embedded/Application/LayerMgr.cpp \
	MapKit/Embedded/Application/Pathfinding.cpp \
	MapKit/Embedded/Application/PathResult.cpp \
	MapKit/Embedded/Application/QueryMgr.cpp \
	MapKit/Embedded/Application/SimuNaviTool.cpp \
	MapKit/Embedded/BasicType/Attribute.cpp \
	MapKit/Embedded/BasicType/Line.cpp \
	MapKit/Embedded/BasicType/Point.cpp \
	MapKit/Embedded/BasicType/Polygon.cpp \
	MapKit/Embedded/BasicType/Rect.cpp \
	MapKit/Embedded/Features/Condense.cpp \
	MapKit/Embedded/Features/Data.cpp \
	MapKit/Embedded/Features/MapLayer.cpp \
	MapKit/Embedded/Features/Visitor.cpp \
	MapKit/Embedded/Network/AdjacencyList.cpp \
	MapKit/Embedded/Network/BindPoint.cpp \
	MapKit/Embedded/Network/HighNetwork.cpp \
	MapKit/Embedded/Network/HighNWSearching.cpp \
	MapKit/Embedded/Network/LookUpTable.cpp \
	MapKit/Embedded/Network/LowNetwork.cpp \
	MapKit/Embedded/Network/LowNWQuadTree.cpp \
	MapKit/Embedded/Network/LowNWSearching.cpp \
	MapKit/Embedded/Network/QuadtreeTable.cpp \
	MapKit/Embedded/Network/Utility.cpp \
	MapKit/Embedded/SpatialIndex/Node.cpp \
	MapKit/Embedded/SpatialIndex/PointBindLine.cpp \
	MapKit/Embedded/SpatialIndex/StaticRTree.cpp \
	MapKit/Embedded/StorageManager/Buffer.cpp \
	MapKit/Embedded/StorageManager/DiskStorageManager.cpp \
	MapKit/Embedded/StorageManager/FIFOBuffer.cpp \
	MapKit/Embedded/StorageManager/StaticDiskStorageManager.cpp \
	MapKit/Embedded/Tools/SpatialMath.cpp \
	MapKit/Embedded/Tools/StringTools.cpp \
	MapKit/Embedded/Tools/Tools.cpp \
	MapKit/GPSWrapper/GPSDataRecord.cpp \
	MapKit/GPSWrapper/GPS_Filter.cpp \
	MapKit/GPSWrapper/GPS_FromLog.cpp \
	MapKit/GPSWrapper/GPS_FromRoute.cpp \
	MapKit/GPSWrapper/GPS_Standard.cpp \
	MapKit/MIFMID/MIF_IO.cpp \
	MapKit/MIFMID/MIF_Adaptor.cpp \
	MapKit/MIFMID/RecordSetImpl.cpp \
	MapKit/RasterImage/Common/CRT_Affine.cpp \
	MapKit/RasterImage/Pyramid/ImagePyramid.cpp \
	MapKit/RasterImage/Pyramid/ImagePyramidUpload.cpp \
	MapKit/RasterImage/Pyramid/Pyramid.cpp \
	MapKit/RasterImage/Pyramid/PyramidRequest.cpp \
	MapKit/RasterImage/Pyramid/PyramidScaler.cpp \
	MapKit/RasterImage/Pyramid/PyramidTileIndex.cpp \
	MapKit/RasterView/CommonStruct.cpp \
	MapKit/RasterView/DataCalculator.cpp \
	MapKit/RasterView/RasterOverlay.cpp \
	MapKit/RasterView/RasterView.cpp \
	MapKit/RasterView/RasterViewController.cpp \
	MapKit/Protocols/MKAnnotation.cpp \
	MapKit/Protocols/MKOverlay.cpp \
	MapKit/Protocols/MKPOIAnnotation.cpp \
	MapKit/DataTypes/Base/MKGeometry.cpp \
	MapKit/DataTypes/Shapes/MKCircle.cpp \
	MapKit/DataTypes/Shapes/MKMultiPoint.cpp \
	MapKit/DataTypes/Shapes/MKPointAnnotation.cpp \
	MapKit/DataTypes/Shapes/MKPolygon.cpp \
	MapKit/DataTypes/Shapes/MKPolyline.cpp \
	MapKit/DataTypes/Shapes/MKShape.cpp \
	MapKit/DataTypes/UserLocation/MKLocationShiftProvider.cpp \
	MapKit/DataTypes/UserLocation/MKUserLocation.cpp \
	MapKit/Fetcher/FetcherThread/FetcherThread.cpp \
	MapKit/Fetcher/StandardDataFetcher/MKStandardDataFetcher.cpp \
	MapKit/Fetcher/StandardDataFetcher/MKStandardDataTiles.cpp \
	MapKit/Fetcher/Pyramid/MKGlobalMapTiles.cpp \
	MapKit/Fetcher/WebDataFetcher/MKWebDataFetcher.cpp \
	MapKit/Fetcher/KMLParser/KMLParser.cpp \
	MapKit/Fetcher/KMLParser/MKKMLContainer.cpp \
	MapKit/Fetcher/KMLParser/MKKMLDocument.cpp \
	MapKit/Fetcher/KMLParser/MKKMLFeature.cpp \
	MapKit/Fetcher/KMLParser/MKKMLFolder.cpp \
	MapKit/Fetcher/KMLParser/MKKMLGeometry.cpp \
	MapKit/Fetcher/KMLParser/MKKMLPlacemark.cpp \
	MapKit/Fetcher/KMLParser/MKKMLSound.cpp \
	MapKit/Fetcher/KMLParser/MKKMLStyle.cpp \
    MapKit/Fetcher/LocalDataFetcher/MKLocalDataFetcher.cpp \
	MapKit/Views/AnnotationViews/MKAnnotationView.cpp \
	MapKit/Views/AnnotationViews/MKPinAnnotationView.cpp \
	MapKit/Views/MapViews/MKMapView.cpp \
	MapKit/Views/MapViews/MKTileLayerOverlay.cpp \
	MapKit/Views/MapViews/MKTileMapView.cpp \
	MapKit/Views/MapViews/MGReusableQueue.cpp \
	MapKit/Views/MapViews/MKMapLayerView.cpp \
	MapKit/Views/MapViews/MKMapScrollView.cpp \
	MapKit/Views/OverlayViews/MKCircleView.cpp \
	MapKit/Views/OverlayViews/MKOverlayPathView.cpp \
	MapKit/Views/OverlayViews/MKOverlayView.cpp \
	MapKit/Views/OverlayViews/MKPolygonView.cpp \
	MapKit/Views/OverlayViews/MKPolylineView.cpp \
	MapKit/Views/AnnotationViews/MKPOIAnnotationView.cpp \
	MapKit/Service/MKPlanNode.cpp \
	MapKit/Service/MKSearch.cpp \
	Retiguide/Analysis/CrossTrans.cpp \
	Retiguide/Analysis/TransformRoad.cpp \
	Retiguide/Analysis/Navigation/Ana_Navigation.cpp \
	Retiguide/Analysis/Navigation/NaviBind.cpp \
	Retiguide/Analysis/Navigation/NavigationInfo.cpp \
	Retiguide/Analysis/Navigation/NaviHandler.cpp \
	Retiguide/Analysis/Navigation/NaviHandlerParam.cpp \
	Retiguide/Analysis/Navigation/NaviPathContext.cpp \
	Retiguide/Analysis/Navigation/NaviProcessor.cpp \
	Retiguide/Analysis/TourGuider/Ana_Query.cpp \
	Retiguide/Common/String_Tools.cpp \
	Retiguide/Common/CRS/ComputeEquation.cpp \
	Retiguide/Common/CRS/CoordSystem.cpp \
	Retiguide/Common/CRS/CRS.cpp \
	Retiguide/Common/CRS/CRS_Factory.cpp \
	Retiguide/Common/CRS/CRS_Generic.cpp \
	Retiguide/Common/CRS/CRS_Geocentric.cpp \
	Retiguide/Common/CRS/CRS_Geography.cpp \
	Retiguide/Common/CRS/CRS_Project.cpp \
	Retiguide/Common/CRS/CRT.cpp \
	Retiguide/Common/CRS/CRTALG_GeographyToGeography.cpp \
	Retiguide/Common/CRS/CRTALG_ProjectionGauss.cpp \
	Retiguide/Common/CRS/CRTALG_ProjectionMercator.cpp \
	Retiguide/Common/CRS/CRTALG_ProjectionMercatorTransverse.cpp \
	Retiguide/Common/CRS/CRT_Compound.cpp \
	Retiguide/Common/CRS/CRT_Conversion.cpp \
	Retiguide/Common/CRS/CRT_Factory.cpp \
	Retiguide/Common/CRS/CRT_GeographyToGeography5480.cpp \
	Retiguide/Common/CRS/CRT_Math.cpp \
	Retiguide/Common/CRS/CRT_NoChange.cpp \
	Retiguide/Common/CRS/CRT_Projection.cpp \
	Retiguide/Common/CRS/CRT_ProjectionGauss.cpp \
	Retiguide/Common/CRS/CRT_ProjectionGauss_Zoned.cpp \
	Retiguide/Common/CRS/CRT_ProjectionLambert.cpp \
	Retiguide/Common/CRS/CRT_ProjectionMercator.cpp \
	Retiguide/Common/CRS/CRT_ProjectionMercatorTransverse.cpp \
	Retiguide/Common/CRS/CRT_ProjectionToProjection5480.cpp \
	Retiguide/Common/CRS/CRT_Transformation.cpp \
	Retiguide/Common/CRS/Datum.cpp \
	Retiguide/Common/CRS/GlobalCrt.cpp \
	Retiguide/Common/CRS/SpatialRefMeta.cpp \
	Retiguide/Common/Share/Scope.cpp \
	Retiguide/Common/Share/ScreenPos2D.cpp \
	Retiguide/Common/Types/FeatureClassInfo.cpp \
	Retiguide/Common/Types/Fraction.cpp \
	Retiguide/Common/Types/GeoTypes/GuiderGeoPoint.cpp \
	Retiguide/Common/Types/GeoTypes/GuiderGeoPointNoTrigger.cpp \
	Retiguide/Common/Types/GeoTypes/GuiderGeoPointTrigger.cpp \
	Retiguide/Common/Types/ProgramLanguage.cpp \
	Retiguide/Common/Types/Settings.cpp \
	Retiguide/Common/Types/Types.cpp \
	Retiguide/Common/Types/DataFetcherTypes/TypeDefs.cpp \
	Retiguide/Common/Types/WorkSpaceTypes/TerrCtrl.cpp \
	Retiguide/Common/Util/Algorithmic.cpp \
	Retiguide/Common/Util/PureMath.cpp \
	Retiguide/Common/Util/ScopeResizer.cpp \
	Retiguide/Common/Util/Transformer.cpp \
	Retiguide/Common/Util/Coordinate/Coordinate.cpp \
	Retiguide/Common/Util/Coordinate/Matrix.cpp \
	Retiguide/Common/Util/Coordinate/Quaternion.cpp \
	Retiguide/Common/Util/Coordinate/Vector3.cpp \
	Retiguide/Common/Util/Coordinate/Vector4.cpp \
	Retiguide/DataFetcher/DataFetcher.cpp \
	Retiguide/DataFetcher/DataFetcherUtil.cpp \
	Retiguide/DataFetcher/DataReader.cpp \
	Retiguide/DataFetcher/DataWriter.cpp \
	Retiguide/DataFetcher/FclsInfoAdapter.cpp \
	Retiguide/DataFetcher/FileAdapter.cpp \
	Retiguide/DataFetcher/FileBuffer.cpp \
	Retiguide/DataFetcher/FileDataFetcher.cpp \
	Retiguide/DataFetcher/GGPointBuffer.cpp \
	Retiguide/DataFetcher/GuiderGeoPointAdapter.cpp \
	Retiguide/DataFetcher/MapConfigAdapter.cpp \
	Retiguide/DataFetcher/PathDef.cpp \
	Retiguide/DataFetcher/ProgramLanguageAdapter.cpp \
	Retiguide/DataFetcher/RadarAdapter.cpp \
	Retiguide/DataFetcher/RamBuffer.cpp \
	Retiguide/DataFetcher/SettingsAdapter.cpp \
	Retiguide/DataFetcher/TerrCtrlAdapter.cpp \
	Retiguide/DataFetcher/TypeDefs.cpp \
	Retiguide/DataFetcher/WorkspaceAdapter.cpp \
	Retiguide/MapViews/CrossView.cpp \
	Retiguide/MapViews/MapView.cpp \
	Retiguide/MapViews/VectorMapView.cpp \
	Retiguide/MapViews/RasterMapView.cpp \
	Retiguide/Render/VctorRender/Annotation/AnnotationLayer.cpp \
	Retiguide/Render/VctorRender/Annotation/AnnotationLayerRender.cpp \
	Retiguide/Render/VctorRender/Annotation/AnnotationLayerStyle.cpp \
	Retiguide/Render/VctorRender/Feature/FeatureLayer.cpp \
	Retiguide/Render/VctorRender/Feature/FeatureLayerRender.cpp \
	Retiguide/Render/VctorRender/Feature/FeatureLayerStyle.cpp \
	Retiguide/Render/VctorRender/Map/MapFrame.cpp \
	Retiguide/Render/VctorRender/Map/MapOpration.cpp \
	Retiguide/Render/VctorRender/Map/MapTerrCtrl.cpp \
	Retiguide/Render/VctorRender/Map/Navigation.cpp \
	Retiguide/Render/VctorRender/Map/ScreenPixMap.cpp \
	Retiguide/Render/VctorRender/Render/StyleRender.cpp \
	Retiguide/Render/VctorRender/Render/StyleTranslate.cpp \
	Retiguide/Render/VctorRender/Render/GmRender/GeoGmImageRender.cpp \
	Retiguide/Render/VctorRender/Render/GmRender/GeoGmLineRender.cpp \
	Retiguide/Render/VctorRender/Render/GmRender/GeoGmPointRender.cpp \
	Retiguide/Render/VctorRender/Render/GmRender/GeoGmPolygonRender.cpp \
	Retiguide/Render/VctorRender/Render/GmRender/GeoGmRender.cpp \
	Retiguide/Render/VctorRender/Render/LabelRender/GeoLabelLineRender.cpp \
	Retiguide/Render/VctorRender/Render/LabelRender/GeoLabelPointRender.cpp \
	Retiguide/Render/VctorRender/Render/LabelRender/GeoLabelPolygonRender.cpp \
	Retiguide/Render/VctorRender/Render/LabelRender/GeoLabelPosTrans.cpp \
	Retiguide/Render/VctorRender/Render/LabelRender/GeoLabelRender.cpp \
	Retiguide/RenderEngine/GmRender/GmStyleRender.cpp \
	Retiguide/RenderEngine/GmRender/LineStyleRender.cpp \
	Retiguide/RenderEngine/GmRender/PointStyleRender.cpp \
	Retiguide/RenderEngine/GmRender/PolygonStyleRender.cpp \
	Retiguide/RenderEngine/ImageRender/ImageStyleRender.cpp \
	Retiguide/RenderEngine/LabelRender/LabelStyleRender.cpp \
	Retiguide/SpatialMath/SpatialMath.cpp \

#	Retiguide/Common/Types/GeoTypes/Types.cpp \


LOCAL_C_INCLUDES+= $($(subst $(WORK_JNI),,$(JNI_DIR)))

LOCAL_STATIC_LIBRARIES :=  CommonBase System GUI wchar_static

include $(BUILD_STATIC_LIBRARY)
